Fix notification LED on jasmine
phhusson/device_phh_treble pull request #49
Opened 2018-09-29 12:38 UTC by p4block

The HAL behaves in mysterious ways and requires this blink file to be writable. Also sync permissions with stock ROM just in case.

2018-09-29 12:41 UTC, phhusson commented
You tested that modified rw-system.sh right?

2018-09-29 13:09 UTC, p4block commented
I patched my current rw-system instead of building a new system, but yes, the files get successfully modified. 

There still seems to be an issue where the LED is randomly initialized to be "on" on android start. 
It seems to be related to charging. If the LED has booted as off, charging will not turn it on. If the LED has booted as on, (and manually turned off), charging will turn it back on. 

I will edit this once I find a final fix.

2018-11-23 04:34 UTC, suwakowww commented
Feedback for wayne:
I tried to modified like this on my phone. (append these commands on the same file but append it after line 137)  But it still "always on" after several reboots, (and turn back normal after reboot twice.)

2018-12-17 21:00 UTC, tytydraco commented
> The HAL behaves in mysterious ways and requires this blink file to be writable. Also sync permissions with stock ROM just in case.

I had my tester give this a shot on the AEX Pie GSI (arm64). It doesn't seem to work. His `duty_pcts` was root:root so I had him chown system:system like stock. No dice.

2018-12-17 21:16 UTC, tytydraco commented
Some more feedback: It breaks itself when plugged into power. However, If one reboots twice (with the cable unplugged), the issue is resolved. However, charging the device will no longer trigger the LED. So it seems that there's most likely an issue with the LED receiving events..?

2019-01-06 01:02 UTC, tytydraco commented
Here's an update on the issue. I discovered the proper commands that need to be executed on boot, located in this device tree file: https://github.com/xiaomi-sdm660/android_device_xiaomi_jasmine/blob/41c4682966532c1195585ed4e40c52a3ed06fc1c/light/android.hardware.light%402.0-service.xiaomi_jasmine.rc

`
on boot
    # Notification LED
    chown system system /sys/class/leds/red/blink
    chown system system /sys/class/leds/red/brightness
    chown system system /sys/class/leds/red/duty_pcts
    chown system system /sys/class/leds/red/pause_hi
    chown system system /sys/class/leds/red/pause_lo
    chown system system /sys/class/leds/red/ramp_step_ms
    chown system system /sys/class/leds/red/start_idx

    chmod 660 /sys/class/leds/red/duty_pcts
    chmod 660 /sys/class/leds/red/pause_hi
    chmod 660 /sys/class/leds/red/pause_lo
    chmod 660 /sys/class/leds/red/ramp_step_ms
    chmod 660 /sys/class/leds/red/start_idx
`

2019-01-06 01:04 UTC, tytydraco requested changes
This device tree file includes all the proper commands necessary for this to work. Please update it based on this:

https://github.com/xiaomi-sdm660/android_device_xiaomi_jasmine/blob/41c4682966532c1195585ed4e40c52a3ed06fc1c/light/android.hardware.light%402.0-service.xiaomi_jasmine.rc

```
on boot
    # Notification LED
    chown system system /sys/class/leds/red/blink
    chown system system /sys/class/leds/red/brightness
    chown system system /sys/class/leds/red/duty_pcts
    chown system system /sys/class/leds/red/pause_hi
    chown system system /sys/class/leds/red/pause_lo
    chown system system /sys/class/leds/red/ramp_step_ms
    chown system system /sys/class/leds/red/start_idx

    chmod 660 /sys/class/leds/red/duty_pcts
    chmod 660 /sys/class/leds/red/pause_hi
    chmod 660 /sys/class/leds/red/pause_lo
    chmod 660 /sys/class/leds/red/ramp_step_ms
    chmod 660 /sys/class/leds/red/start_idx
```

2019-01-30 15:13 UTC, penn5 commented
@p4block this fixes on Oreo vendor, Pie vendor or both?

2019-02-01 12:49 UTC, kvsjxd commented
@tytydraco Yes. I was the tester. Btw are there any updates on this issue? @phhusson

2019-05-26 16:28 UTC, tytydraco commented
Please close this thread. A proper fix was merged into the main branch.

2019-05-26 16:36 UTC, closed without merging