Added support Motorola Pettyl & James -wh0dat
phhusson/device_phh_treble pull request #88
Opened 2019-02-06 15:33 UTC by wh0dat

Added support Motorola Pettyl & James -wh0dat

2019-02-06 15:39 UTC, penn5 requested changes

2019-02-06 15:39 UTC, penn5 commented on rw-system.sh
> +    if getprop ro.vendor.product.device |grep -q -e nora -e ali -e hannah -e pettyl -e james;then
This should be tabs...
```suggestion
	if getprop ro.vendor.product.device |grep -q -e nora -e ali -e hannah -e pettyl -e james;then
```

2019-02-06 15:39 UTC, penn5 commented on rw-system.sh
>          mount -o bind /mnt/phh/empty_dir /vendor/lib/soundfx
this should also be tabs, but maybe in a seperate commit?

2019-03-04 20:56 UTC, phhusson commented
added in https://github.com/phhusson/device_phh_treble/commit/a8b1cfb7cbcb08e3557c6ca0daa6c5c822f09fa0

2019-03-04 21:04 UTC, closed without merging